# NumPy ufuncs

### What are ufuncs?

ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.

### Why use ufuncs?

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

**where** boolean array or condition defining where the operations should take place.

**dtype** defining the return type of elements.

**out** output array where the return value should be copied.

### What is Vectorization?

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

Add the Elements of Two Lists
list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements.

In [1]:
import numpy as np

In [2]:
# Without ufunc, we can use Python's built-in zip() method:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = []

for i, j in zip(arr1, arr2):
    arr.append(i+j)

print(arr)

[5, 7, 9]


In [3]:
# NumPy has a ufunc for this, called add(x, y) that will produce the same result.

# Example
# With ufunc, we can use the add() function:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.add(arr1, arr2)

print(arr)

[5 7 9]


## Create Your Own ufunc

How To Create Your Own ufunc

To create you own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

***function*** - the name of the function.

***inputs*** - the number of input arguments (arrays).

***outputs*** - the number of output arrays.

In [4]:
def myadd(x, y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3], [4, 5, 6]))

[5 7 9]


### Check if a Function is a ufunc

In [5]:
print(type(np.add))

<type 'numpy.ufunc'>


In [6]:
print(type(np.concatenate))

<type 'builtin_function_or_method'>


In [7]:
if type(np.add) == np.ufunc:
    print("add is ufunc")
else:
    print("add is not ufunc")

add is ufunc


# Simple Arithmetic

In [8]:
# add

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

new = np.add(arr1, arr2)

print(new)

[30 32 34 36 38 40]


In [9]:
# subtract

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

new = np.subtract(arr2, arr1)

print(new)

[10 10 10 10 10 10]


In [10]:
#multiply

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

new = np.multiply(arr2, arr1)

print(new)

[200 231 264 299 336 375]


In [11]:
# divide

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

new = np.divide(arr2, arr1)

print(new)

[2 1 1 1 1 1]


In [12]:
# power

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([2, 3, 4, 5, 2, 3])

new = np.power(arr1, arr2)

print(new)

[   100   1331  20736 371293    196   3375]


In [13]:
# remainder

arr1 = np.array([10, 11, 15, 13, 14, 20])
arr2 = np.array([2, 3, 4, 5, 2, 3])

new = np.mod(arr1, arr2)

print(new)

[0 2 3 3 0 2]


In [14]:
# remainder

arr1 = np.array([10, 11, 15, 13, 14, 20])
arr2 = np.array([2, 3, 4, 5, 2, 3])

new = np.remainder(arr1, arr2)

print(new)

[0 2 3 3 0 2]


### Quotient and Mod

In [15]:
arr1 = np.array([10, 11, 15, 13, 14, 20])
arr2 = np.array([2, 3, 4, 5, 2, 3])

new = np.divmod(arr1, arr2)

print(new)

(array([5, 3, 3, 2, 7, 6]), array([0, 2, 3, 3, 0, 2]))


In [16]:
# Absolute Values

arr2 = np.array([2, -3, 4, -5, -2, 3])

new = np.absolute(arr2)

print(new)

[2 3 4 5 2 3]


# Rounding Decimals

Rounding Decimals

There are primarily five ways of rounding off decimals in NumPy:

* truncation
* fix
* rounding
* floor
* ceil

**Truncation**

Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [17]:
arr = np.array([2.455, -3.45612, 4.123, -5.753, -2.951, 3.4560])

new = np.trunc(arr)

print(new)

[ 2. -3.  4. -5. -2.  3.]


In [18]:
arr = np.array([2.455, -3.45612, 4.123, -5.753, -2.951, 3.4560])

new = np.fix(arr)

print(new)

[ 2. -3.  4. -5. -2.  3.]


### Rounding

The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2



In [19]:
new = np.around(3.1956, 2)

print(new)

3.2


In [20]:
# floor
# The floor() function rounds off decimal to nearest lower integer.
# E.g. floor of 3.166 is 3.

arr = np.array([2.455, -3.45612, 4.123, -5.753, -2.951, 3.4560])

new = np.floor(arr)

print(new)

[ 2. -4.  4. -6. -3.  3.]


In [21]:
# Ceil
# The ceil() function rounds off decimal to nearest upper integer.
# E.g. ceil of 3.166 is 4.

arr = np.array([2.455, -3.45612, 4.123, -5.753, -2.951, 3.4560])

new = np.ceil(arr)

print(new)

[ 3. -3.  5. -5. -2.  4.]


# NumPy Logs
### Logs

NumPy provides functions to perform log at the base 2, e and 10.

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place -inf or inf in the elements if the log can not be computed.



In [22]:
# log at base 2

arr = np.arange(1, 11)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]


In [23]:
# log at base 10

arr = np.arange(1, 11)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]


### Natural Log, or Log at Base e

Use the log() function to perform log at the base e.

In [24]:
arr = np.arange(1, 11)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


### Log at Any Base

NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [25]:
from math import log

mylog = np.frompyfunc(log, 2, 1)

print(mylog(100, 15))

1.70054830746


# NumPy Summations

Summations
What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [26]:
# Add the values in arr1 to the values in arr2:

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [27]:
# Sum the values in arr1 and the values in arr2:

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


### Summation Over an Axis

If you specify axis=1, NumPy will sum the numbers in each array.

Example
Perform summation in the following array over 1st axis:

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


### Cummulative Sum

In [29]:
arr1 = np.array([1, 2, 3])

newarr = np.cumsum(arr1)

print(newarr)

[1 3 6]


# NumPy Products

Products

To find the product of the elements in an array, use the prod() function.

In [30]:
arr1 = np.array([1, 2, 3, 4])

new = np.prod(arr1)

print(new)

24


In [31]:
arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([5, 6, 7, 8])

new = np.prod([arr1, arr2])

print(new)

40320


In [32]:
arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([5, 6, 7, 8])

new = np.prod([arr1, arr2], axis=1)

print(new)

[  24 1680]


### Cummulative Product

In [33]:
arr1 = np.array([1, 2, 3, 4])

new = np.cumprod(arr1)

print(new)

[ 1  2  6 24]


# NumPy Differences

Differences
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.



In [34]:
arr1 = np.array([1, 2, 3, 4])

new = np.diff(arr1)

print(new)

[1 1 1]


In [35]:

arr1 = np.array([10, 15, 25, 5])

new = np.diff(arr1)

print(new)

[  5  10 -20]


In [36]:
# Compute discrete difference of the following array twice:

arr1 = np.array([10, 15, 25, 5])

new = np.diff(arr1, n = 2)

print(new)

[  5 -30]


# NumPy LCM Lowest Common Multiple

Finding LCM (Lowest Common Multiple)

The Lowest Common Multiple is the least number that is common multiple of both of the numbers.

In [37]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


### Finding LCM in Arrays

To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.



In [38]:
arr1 = np.array([3, 6, 9])

x = np.lcm.reduce(arr1)

print(x)

18


In [39]:
# Find the LCM of all of an array where the array contains all integers from 1 to 10:

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


# NumPy GCD Greatest Common Denominator

Finding GCD (Greatest Common Denominator)

The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.

In [40]:
num1 = 9
num2 = 6

x = np.gcd(num1, num2)

print(x)

3


In [41]:
# Finding GCD in Arrays
#To find the Highest Common Factor of all values in an array, you can use the reduce() method.

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


# NumPy Trigonometric Functions


In [42]:
# Find sine value of PI/2:

x = np.sin(np.pi / 2)

print(x)

1.0


In [43]:
# Find sine values for all of the values in arr:

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [44]:
# Convert all of the values in following array arr to radians:

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [45]:
# Convert all of the values in following array arr to degrees:

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


# Finding Angles
Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [46]:
x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [47]:
# angle of each value in array 

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


### Hypotenues

Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.



In [48]:
base = 3
preg = 4

x = np.hypot(base, preg)

print(x)

5.0


# NumPy Hyperbolic Functions

In [49]:

x = np.sinh(np.pi / 2)

print(x)

2.3012989023072947


In [50]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


Finding Angles

Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.



In [51]:
x = np.arcsinh(1.0)

print(x)

0.881373587019543


In [52]:

arr = np.array([1, -1, 0.1])

x = np.arcsinh(arr)

print(x)

[ 0.88137359 -0.88137359  0.09983408]


# NumPy Set Operations

What is a Set

A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

In [53]:
# Create Sets in NumPy
# We can use NumPy's unique() method to find unique elements from any array. 
# E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [54]:
# Finding Union

# To find the unique values of two arrays, use the union1d() method.


arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

x = np.union1d(arr1, arr2)

print(x)

[1 2 3 4 5 6]


In [55]:
# Finding Intersection

# To find only the values that are present in both arrays, use the intersect1d() method.

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

x = np.intersect1d(arr1, arr2)

print(x)

[3 4]


### Finding Difference

To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.



In [56]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

x = np.setdiff1d(arr1, arr2, assume_unique = True)

print(x)

[1 2]


### Finding Symmetric Difference

To find only the values that are NOT present in BOTH sets, use the setxor1d() method.



In [57]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

x = np.setxor1d(arr1, arr2, assume_unique = True)

print(x)

[1 2 5 6]
