# numpy learning

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
print(np.__version__)

1.16.6


In [4]:
print(type(arr))

<type 'numpy.ndarray'>


## Dimensions in Arrays

### 0-D

In [5]:
prr = np.array(45)

print(prr)

45


## 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [6]:
prr = np.array([1, 5, 4, 6 ,8])

print(prr)

[1 5 4 6 8]


## 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

In [7]:
prr = np.array([[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]])

print(prr)

[[ 1  5  4  6  8]
 [45 52 45 63 96]]


## 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [8]:
prr = np.array([[[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]], [[45, 10, 85, 96, 74], [85, 96, 63, 32, 52]]])

print(prr)

[[[ 1  5  4  6  8]
  [45 52 45 63 96]]

 [[45 10 85 96 74]
  [85 96 63 32 52]]]


# Check Number of Dimensions?

In [9]:
prr = np.array([[[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]], [[45, 10, 85, 96, 74], [85, 96, 63, 32, 52]]])

print(prr.ndim)

prr = np.array([[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]])

print(prr.ndim)

prr = np.array([1, 5, 4, 6 ,8])

print(prr.ndim)

prr = np.array(45)

print(prr.ndim)

3
2
1
0


## Higher Diensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.


In [10]:
pr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(pr)

print(pr.ndim)

[[[[[1 2 3 4 5]]]]]
5


# NumPy Array Indexing

In [11]:
prr = np.array([1, 5, 4, 6 ,8])

print(prr[1])

5


In [12]:
prr = np.array([[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]])

print(prr[0, 3])

print(prr[1, 4])

6
96


In [13]:
prr = np.array([[[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]], [[45, 10, 85, 96, 74], [85, 96, 63, 32, 52]]])

print(prr[0, 1, 1])

print(prr[1, 0, 4])

52
74


## Negative Indexing 

In [14]:
prr = np.array([1, 5, 4, 6 ,8])

print(prr[-2])

6


In [15]:
prr = np.array([[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]])

print(prr[1, -3])

45


In [16]:
prr = np.array([[[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]], [[45, 10, 85, 96, 74], [85, 96, 63, 32, 52]]])

print(prr[-2, -1, -4])

52


# NumPy Array Slicing

In [17]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15])

print(prr[2:4])

print(prr[::2])

[4 6]
[ 1  4  8 10]


In [18]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15])

print(prr[-5:-2])

[6 8 7]


In [19]:
prr = np.array([[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]])

print(prr[:, 1:3])

print(prr[1, :4])

print(prr[:, 1])

[[ 5  4]
 [52 45]]
[45 52 45 63]
[ 5 52]


# NumPy Data Types

## Checking the Data Type of an Array

In [20]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15])

print(prr.dtype)

int64


In [21]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

|S6


In [22]:
arr = np.array([10.45, 45.78, 78.45])

print(arr.dtype)

float64


## Creating Arrays With a Defined Data Type


In [23]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15], dtype='S')

print(prr)

print(prr.dtype)

['1' '5' '4' '6' '8' '7' '10' '15']
|S2


In [24]:
arr = np.array([10.45, 45.78, 78.45])

prr = arr.astype('i')

print(prr)

print(prr.dtype)

[10 45 78]
int32


In [25]:
arr = np.array([10.45, 0, 78.45])

prr = arr.astype(bool)

print(prr)

print(prr.dtype)

[ True False  True]
bool


# NumPy Array Copy vs View


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [26]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15])

arr = prr.copy()

print(prr)

print(arr)

arr[0] = 100

print(prr)

print(arr)

[ 1  5  4  6  8  7 10 15]
[ 1  5  4  6  8  7 10 15]
[ 1  5  4  6  8  7 10 15]
[100   5   4   6   8   7  10  15]


In [27]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15])

arr = prr.view()

print(prr)

print(arr)

arr[0] = 100

print(prr)

print(arr)

[ 1  5  4  6  8  7 10 15]
[ 1  5  4  6  8  7 10 15]
[100   5   4   6   8   7  10  15]
[100   5   4   6   8   7  10  15]


# Check if Array Owns it's Data

In [28]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15])

x = prr.copy()

y = prr.view()

print(x.base)

print(y.base)

None
[ 1  5  4  6  8  7 10 15]


# NumPy Array Shape

In [29]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15])

print(prr.shape)

(8,)


In [30]:
prr = np.array([[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]])

print(prr.shape)

(2, 5)


In [31]:
prr = np.array([1, 5, 4, 6 ,8, 7, 10, 15], ndmin=5)

print(prr.shape)

(1, 1, 1, 1, 8)


# NumPy Array Reshaping

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

prr = arr.reshape(4, 3)

print(prr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

prr = arr.reshape(2, 2, 3)

print(prr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Returns Copy or View?

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.reshape(4, 3).base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.



In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

prr = arr.reshape(2, 2, -1)

print(prr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.



In [36]:
prr = np.array([[1, 5, 4, 6 ,8], [45, 52, 45, 63, 96]])

arr = prr.reshape(-1)

print(arr)

[ 1  5  4  6  8 45 52 45 63 96]


# NumPy Array Iterating

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for i in arr:
    print(i)

1
2
3
4
5
6
7
8


In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [40]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [41]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
    for j in i:
        print(j)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [42]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Arrays Using nditer()

In [43]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for j in np.nditer(arr):
    print(j)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating With Different Step Size

We can use filtering and followed by iteration.

In [44]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for ind, i in np.ndenumerate(arr):
    print(ind, i)

((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)
((4,), 5)
((5,), 6)
((6,), 7)
((7,), 8)


In [46]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


for ind, i in np.ndenumerate(arr):
    print(ind, i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)


# NumPy Joining Array

In [47]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [48]:
arr1 = np.array([[1, 2, 3], [5, 6, 7]])

arr2 = np.array([[4, 5, 6], [7, 8, 9]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 3 4 5 6]
 [5 6 7 7 8 9]]


## Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.



In [49]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Stacking Along Rows

NumPy provides a helper function: hstack() to stack along rows.


In [50]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns

NumPy provides a helper function: vstack()  to stack along columns.



In [51]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Height (depth)

NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [52]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array

In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new = np.array_split(arr, 3)

print(new)

arr = np.array([1, 2, 3, 4, 5, 6])

new = np.array_split(arr, 4)

print(new)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


## Split Into Arrays

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new = np.array_split(arr, 3)

print(new[0])
print(new[1])
print(new[2])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


## Splitting 2-D Arrays

Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.



In [55]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

print(arr)

newarr = np.array_split(arr, 3)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


**In addition, you can specify which axis you want to do the split around.**

**The example below also returns three 2-D arrays, but they are split along the row (axis=1).**


In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new = np.array_split(arr, 3, axis=1)

print(new)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new = np.hsplit(arr, 3)

print(new)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Use the vsplit() method to split the 2-D array into three 2-D arrays along column.

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new = np.vsplit(arr, 3)

print(new)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# NumPy Searching Arrays

In [59]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [60]:
#indexes where value is even

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr % 2 == 0)

print(x)

(array([1, 3, 5, 6]),)


In [61]:
# Find the indexes where the values are odd:

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr % 2 != 0)

print(x)

(array([0, 2, 4]),)


## Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])

x = np.searchsorted(arr, 5)

print(x)

4


### Find the indexes where the value 7 should be inserted, starting from the right:

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6])

x = np.searchsorted(arr, 5, side='right')

print(x)

5


### Find the indexes where the values 2, 3, and 6 should be inserted:



In [64]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 3, 6])

print(x)

[1 1 3]


# NumPy Sorting Arrays

In [65]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [66]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [67]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [68]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy Filter Array

Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [69]:
arr = np.array([1, 2, 3, 4])

x = [True, False, True, False]

new = arr[x]

print(new)

[1 3]


In [70]:
# Create a filter array that will return only values higher than 10:
arr = np.array([1, 15, 3, 20])

filtr = []

for i in arr:
    if i > 10:
        filtr.append(True)
    else:
        filtr.append(False)

new = arr[filtr]

print(new)

[15 20]


In [71]:
# Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

fil = []

for i in arr:
    if i % 2 == 0:
        fil.append(True)
    else:
        fil.append(False)

new = arr[fil]
print(new)

[2 4 6]


In [72]:
# Create a filter array that will return only values higher than 10:
arr = np.array([1, 15, 3, 20])

filtr = arr > 10

new = arr[filtr]

print(new)

[15 20]


In [73]:
# Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

fil = arr % 2 == 0

new = arr[fil]
print(new)

[2 4 6]
